language: ruby
rvm:
- 2.4
branches:
  only:
  - gh-pages
script:
- bundle exec jekyll build --config _config.yml
- bundle exec htmlproofer ./_site --external_only --only-4xx --url-ignore \"/#.*/,/getting-started\"
env:
  global:
    secure: XndXk7azIn5a624SfiUdY/2ALwF6V34WWIHNQNZtSthDtLo+PsD9tx1p0u61eDu9+XaEU/9EwkALkSJBWNo2lEeQ3JDvP+PPfwyniqBJ/nttA/463ikLTkB0I+u7LXgnIAdQO4vDiYbDYv1B554TqNqV//bVfCLaSqMVjastt0Nqha8WCh3XU0aeb68Fa5D2SOD9KWzkTpZEymfk/odUKuBW3cXCAXX52wEHzb8NPbzgnu4D1rFFXDv4zUMulOy8CKGEnvrGsN1kvKaLyOVm4+/fDeFFdjjDU3osWdcYLZMthcAgF48Jn75iGK+I6gXqayqUIxrVD4BzyxmQeZmqblgvc2lBGG4yBnpGwRPyExFKI0ity2T8qMziNTd9vlstd3sqbmRY86jDsNNnCeTqny14X7qb4sw0TDHQJnbtr48qrtPoCtXHgmtQ+/mLhhwvymnzfTCs+tRLb4JzH1lndw4aGd0+g4JvQSQBqnUIV6EgD6jNJHmZjSmYwCH4s2ZMYS7XdExYghHktBWozBaCbqck+U5I+zypsoj7cJxt1GtNusHBWqeKzCs4ff0O2Mf51oNzzoMm+5v3DFBts9z7BFf3IIijeQQn3HqvXepJrHZpF2thzls0ouxQJHXlVageDj1348hWsdXxsKkNjwNoaOyUTgxhHgaQ0erXIYIPkOo=
dd:
  secure: C4vrtUCUVUfFC/XydsJ3hrXmdt/5PCAhgtrPR76gc4MsL7SilsgoPxSqXJcVrPKxFQIBsKZJTSkn1RB9s4odPmN9hPeUrfyxZM+iJ23F6+EhendYz77H36Zm1ZATVKu7Dh++2oRIugl1ybtEVBmef89uxUSz3GIDRex9FGTkEn8FyF8zCN6uR7PCSQFeGTPpwb/vv2XssFMjJpjPfyL4/jWmE+8O2GfLFR3W8VhdfLU2kKE73UJEbkrjTJsQnM8HUGZO9e8fTTUqJCAnTAreAx4u7MMN/8dUN7cdl2xHgNn/dpWJV60ISAaORJIUI2z22beG+w5YTIh63nwUhs6vIf5olVfraei+42PRJXchJIGtE1DwP/6kSfUeiQaL3zcRVaPTL+GkckcZfwTo0EOoGQFmqahw/02DpEYTmkJ3AZZhppXpe1nZRG9qQJRGPALv7K3oPmYIYvkvXeyq8s5X8NOVKbd2LM9CQHhnZa+aFH58xg/lj+KIIGmC349X04WZ8lChQncuur07BKJe5FQHZyzXTV+9c/7N4gMKUuEnXiRaVxRV5YwopM+B6piyCIqK2tR0GOwY4wKKhGs5r1oW1QPeDoZvEJuElo9eLX8y7w/DC68yCUKG3HcSK2p15nn0HJuo0AJlLtKUKGwz8mFH5Jiz7ejZXjm+Rcu9nrjfU8c=
